trigger:
  branches:
    include:
      - master
  paths:
    include:
      - IAC_AppServicePlan/**

variables:
  azureServiceConnection: 'demo-wif-auto'
  subscriptionId: '826d75e6-31fb-4b04-b9d6-50cfa34b5db2'
  resourceGroupName: 'rg-juiceshop'
  location: 'eastus'

stages:
- stage: Deploy
  displayName: 'Create Infrastructure'
  jobs:
  - job: Infrastructure
    displayName: 'Create Resource Group and App Service Plan'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Task 1 - Create Resource Group and App Service Plan
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy Bicep - Resource Group & App Service Plan'
      inputs:
        deploymentScope: 'Subscription'        # ← Subscription level to create RG
        azureResourceManagerConnection: 'demo-wif-auto'
        subscriptionId: '826d75e6-31fb-4b04-b9d6-50cfa34b5db2'
        location: 'eastus'
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)/IAC_AppServicePlan/main.bicep'
        deploymentMode: 'Incremental'